### ISSUE TITLE
(Request) Please add an Option/Config to change aim and fire buttons

### ISSUE THREAD

**Issue by CaelTheColher** [elidhan/Simple-Animated-Guns#14]
Currently the fire and aim buttons are tied to the place and break buttons respectively, making it so aim is on left mouse button and fire is on right mouse button which really confuses me since in most if not all FPS games its the opposite

**Comment by elidhan** [comment]
In the recent pushes (update unreleased yet), shooting is now tied to the attack button while aiming is tied to the use button. Will try to release a beta on the weekends after finishing the upcoming guns as well as their respective blueprints and recipes

**Comment by CaelTheColher** [comment]
I see, thank you for your time
