### ISSUE TITLE
1.20.1?

### ISSUE THREAD

**Issue by Blayung** [elidhan/Simple-Animated-Guns#8]
I've seen some commits reffering to 1.20.1, and it seems like it should be already working, however you didn't make any releases for  1.20.1 yet. Will it be stable and compatible with future versions if I just compile the 1.20.1 version now?

**Comment by elidhan** [comment]
Stable yes, the important bits all seem to be working fine. You may if you want to, but there's still some unfinished stuff such as the anti-materiel rifle, minigun, several tweaks and bug fixes that I haven't pushed yet, etc.

**Comment by Blayung** [comment]
Oki

**Comment by Blayung** [comment]
I've seen you've released some 1.20.1 betas, I'm going to close this issue.
